language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
after_success:
- cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - master
